{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import traceback\n",
    "from pymongo import MongoClient\n",
    "from elasticsearch import Elasticsearch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "db = MongoClient('mongodb://127.0.0.1:27017')['Dogforum']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "es = Elasticsearch()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "12"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(db.collection_names())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "text_mapping = {\n",
    "  \"type\": \"text\",\n",
    "  \"fields\": {\n",
    "    \"keyword\": {\n",
    "      \"type\": \"keyword\",\n",
    "      \"ignore_above\": 256\n",
    "    }\n",
    "  }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "n_gram = {\n",
    "  \"type\": \"text\",\n",
    "  \"analyzer\": \"autocomplete\",\n",
    "  \"search_analyzer\": \"autocomplete_search\",\n",
    "  \"fields\": {\n",
    "    \"keyword\": {\n",
    "      \"type\": \"keyword\",\n",
    "      \"ignore_above\": 256\n",
    "    }\n",
    "  }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "def index_map(type_name):\n",
    "    _index_mappings = {\n",
    "      \"settings\": {\n",
    "        \"analysis\": {\n",
    "          \"analyzer\": {\n",
    "            \"autocomplete\": {\n",
    "              \"tokenizer\": \"autocomplete\",\n",
    "              \"filter\": [\n",
    "                \"lowercase\"\n",
    "              ]\n",
    "            },\n",
    "            \"autocomplete_search\": {\n",
    "              \"tokenizer\": \"lowercase\"\n",
    "            }\n",
    "          },\n",
    "          \"tokenizer\": {\n",
    "            \"autocomplete\": {\n",
    "              \"type\": \"edge_ngram\",\n",
    "              \"min_gram\": 3,\n",
    "              \"max_gram\": 10,\n",
    "              \"token_chars\": [\n",
    "                \"letter\"\n",
    "              ]\n",
    "            }\n",
    "          }\n",
    "        }\n",
    "      },\n",
    "      \"mappings\": {\n",
    "         type_name: {\n",
    "          \"properties\": {\n",
    "            \"author_info\": {\n",
    "              \"properties\": {\n",
    "                \"join_date\": text_mapping,\n",
    "                \"location\": text_mapping,\n",
    "                \"member_type\": text_mapping,\n",
    "                \"mentioned\": text_mapping,\n",
    "                \"posts\": text_mapping,\n",
    "                \"tagged\": text_mapping\n",
    "              }\n",
    "            },\n",
    "            \"author_name\": text_mapping,\n",
    "            \"author_url\": text_mapping,\n",
    "            \"content\": n_gram,\n",
    "            \"floor\": {\n",
    "              \"type\": \"integer\"\n",
    "            },\n",
    "            \"id\": text_mapping,\n",
    "            \"page\": text_mapping,\n",
    "            \"post_date\": {\n",
    "              \"properties\": {\n",
    "                \"ampm\": text_mapping,\n",
    "                \"date\": {\n",
    "                  \"type\": \"date\",\n",
    "                  \"format\": \"MM-dd-yyyy||strict_year_month_day\"\n",
    "                },\n",
    "                \"time\": {\n",
    "                  \"type\": \"date\",\n",
    "                  \"format\": \"HH:mm||strict_hour_minute\"\n",
    "                }\n",
    "              }\n",
    "            },\n",
    "            \"p_date\": {\n",
    "            \"type\": \"integer\"\n",
    "            },\n",
    "            \"title\": n_gram,\n",
    "            \"quotation\": n_gram,\n",
    "            \"url\":text_mapping\n",
    "          }\n",
    "        }\n",
    "      }\n",
    "    }\n",
    "    return _index_mappings"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# if es.indices.exists(index='dogforum') is not True:\n",
    "#    es.indices.create(index='dogforum', body=index_map(type_name))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Grooming\n",
      "New_Additions\n",
      "Train_Behavior\n"
     ]
    }
   ],
   "source": [
    "for type_name in db.collection_names()[:3]:\n",
    "    es.indices.create(index='dogforum', body=index_map(type_name))\n",
    "    print(type_name)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# For single insert"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "cursor = db[type_name].find({}, projection={'_id':False})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "_docs = [x for x in cursor]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "_docs[1].get('id').replace('/','')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "for _doc in _docs[:10]:\n",
    "    print(_doc.get('id').replace('/',''))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorforum-rules-guidelines-training-behavior-please-4330 [status:400 request:0.009s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorattending-workshops-conferences-reviews-tips-more-107497 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviorattending-workshops-conferences-reviews-tips-more-107497 [status:400 request:0.008s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor3dog-training-behaviorattending-workshops-conferences-reviews-tips-more-107497 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviordogforum-com-rules-103546 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorworkshop-conference-announcements-107489 [status:400 request:0.006s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviorworkshop-conference-announcements-107489 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor3dog-training-behaviorworkshop-conference-announcements-107489 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor4dog-training-behaviorworkshop-conference-announcements-107489 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor5dog-training-behaviorworkshop-conference-announcements-107489 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor6dog-training-behaviorworkshop-conference-announcements-107489 [status:400 request:0.006s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor7dog-training-behaviorworkshop-conference-announcements-107489 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor8dog-training-behaviorworkshop-conference-announcements-107489 [status:400 request:0.008s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor9dog-training-behaviorworkshop-conference-announcements-107489 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor10dog-training-behaviorworkshop-conference-announcements-107489 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833 [status:400 request:0.007s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor3dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor4dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor5dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor6dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833 [status:400 request:0.006s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor7dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor8dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor9dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor10dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviordog-scratches-empty-plate-after-meal-351826 [status:400 request:0.005s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviordog-scratches-empty-plate-after-meal-351826 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor3dog-training-behaviordog-scratches-empty-plate-after-meal-351826 [status:400 request:0.003s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'failed to parse [post_date.date]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorunruly-puppy-351962 [status:400 request:0.004s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'failed to parse [post_date.date]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviorunruly-puppy-351962 [status:400 request:0.003s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'failed to parse [post_date.date]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor11dog-training-behaviorworkshop-conference-announcements-107489page2 [status:400 request:0.008s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor12dog-training-behaviorworkshop-conference-announcements-107489page2 [status:400 request:0.005s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor13dog-training-behaviorworkshop-conference-announcements-107489page2 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor14dog-training-behaviorworkshop-conference-announcements-107489page2 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor15dog-training-behaviorworkshop-conference-announcements-107489page2 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor16dog-training-behaviorworkshop-conference-announcements-107489page2 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor17dog-training-behaviorworkshop-conference-announcements-107489page2 [status:400 request:0.005s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor18dog-training-behaviorworkshop-conference-announcements-107489page2 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor19dog-training-behaviorworkshop-conference-announcements-107489page2 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor20dog-training-behaviorworkshop-conference-announcements-107489page2 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor11dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833page2 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor12dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833page2 [status:400 request:0.011s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor13dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833page2 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor14dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833page2 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor15dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833page2 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor16dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833page2 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor17dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833page2 [status:400 request:0.006s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor18dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833page2 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor19dog-training-behaviorshamas-progress-little-frustratred-mostly-engouraged-345833page2 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page3Floor21dog-training-behaviorworkshop-conference-announcements-107489page3 [status:400 request:0.004s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page3Floor22dog-training-behaviorworkshop-conference-announcements-107489page3 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page3Floor23dog-training-behaviorworkshop-conference-announcements-107489page3 [status:400 request:0.006s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page3Floor24dog-training-behaviorworkshop-conference-announcements-107489page3 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page3Floor25dog-training-behaviorworkshop-conference-announcements-107489page3 [status:400 request:0.009s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page3Floor26dog-training-behaviorworkshop-conference-announcements-107489page3 [status:400 request:0.004s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page3Floor27dog-training-behaviorworkshop-conference-announcements-107489page3 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behavior9-week-old-husky-terrified-hands-351378 [status:400 request:0.008s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behavior9-week-old-husky-terrified-hands-351378 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor3dog-training-behavior9-week-old-husky-terrified-hands-351378 [status:400 request:0.009s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor4dog-training-behavior9-week-old-husky-terrified-hands-351378 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor5dog-training-behavior9-week-old-husky-terrified-hands-351378 [status:400 request:0.008s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor6dog-training-behavior9-week-old-husky-terrified-hands-351378 [status:400 request:0.006s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor7dog-training-behavior9-week-old-husky-terrified-hands-351378 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor8dog-training-behavior9-week-old-husky-terrified-hands-351378 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor9dog-training-behavior9-week-old-husky-terrified-hands-351378 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor10dog-training-behavior9-week-old-husky-terrified-hands-351378 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorexpectations-puppy-training-351626 [status:400 request:0.005s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviorexpectations-puppy-training-351626 [status:400 request:0.009s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor3dog-training-behaviorexpectations-puppy-training-351626 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor4dog-training-behaviorexpectations-puppy-training-351626 [status:400 request:0.008s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor5dog-training-behaviorexpectations-puppy-training-351626 [status:400 request:0.009s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor6dog-training-behaviorexpectations-puppy-training-351626 [status:400 request:0.008s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorsudden-behavior-changes-351834 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviorsudden-behavior-changes-351834 [status:400 request:0.003s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'failed to parse [post_date.date]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page2Floor11dog-training-behavior9-week-old-husky-terrified-hands-351378page2 [status:400 request:0.008s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorhelp-getting-dog-drop-items-like-351754 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviorhelp-getting-dog-drop-items-like-351754 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor3dog-training-behaviorhelp-getting-dog-drop-items-like-351754 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor4dog-training-behaviorhelp-getting-dog-drop-items-like-351754 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor5dog-training-behaviorhelp-getting-dog-drop-items-like-351754 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorpuppy-porch-anxiety-351786 [status:400 request:0.004s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorfoster-dog-barks-living-room-when-351674 [status:400 request:0.004s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviorfoster-dog-barks-living-room-when-351674 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor3dog-training-behaviorfoster-dog-barks-living-room-when-351674 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorpotty-training-other-problems-seperation-349634 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviorpotty-training-other-problems-seperation-349634 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor3dog-training-behaviorpotty-training-other-problems-seperation-349634 [status:400 request:0.010s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorcatahoula-biting-nipping-people-they-walking-351762 [status:400 request:0.009s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorpuppy-pooping-couch-potty-training-not-351730 [status:400 request:0.009s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorfirst-time-dog-owner-needs-help-351610 [status:400 request:0.008s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviorfirst-time-dog-owner-needs-help-351610 [status:400 request:0.010s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor3dog-training-behaviorfirst-time-dog-owner-needs-help-351610 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor4dog-training-behaviorfirst-time-dog-owner-needs-help-351610 [status:400 request:0.006s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorpersistant-chewer-351682 [status:400 request:0.005s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorsevere-separation-anxiety-puppy-351666 [status:400 request:0.007s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor1dog-training-behaviorgrieving-frustrated-351514 [status:400 request:0.011s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor2dog-training-behaviorgrieving-frustrated-351514 [status:400 request:0.008s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor3dog-training-behaviorgrieving-frustrated-351514 [status:400 request:0.006s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor4dog-training-behaviorgrieving-frustrated-351514 [status:400 request:0.009s]\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n",
      "PUT http://localhost:9200/dogforum/Train_Behavior/Page1Floor5dog-training-behaviorgrieving-frustrated-351514 [status:400 request:0.007s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processed: 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-18-9e01d2b1b11a>\", line 4, in <module>\n",
      "    es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n",
      "    return func(*args, params=params, **kwargs)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 300, in index\n",
      "    _make_path(index, doc_type, id), params=params, body=body)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/transport.py\", line 314, in perform_request\n",
      "    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 163, in perform_request\n",
      "    self._raise_error(response.status, raw_data)\n",
      "  File \"/home/iii/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n",
      "    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n",
      "elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [dogforum] as the final mapping would have more than 1 type: [Train_Behavior, Grooming]')\n"
     ]
    }
   ],
   "source": [
    "processed = 0\n",
    "for _doc in _docs[:100]:\n",
    "    try:\n",
    "        es.index(index='dogforum', doc_type=type_name, id=_doc.get('id').replace('/',''), body=_doc)\n",
    "        processed += 1\n",
    "    except:\n",
    "        traceback.print_exc()\n",
    "print('Processed: ' + str(processed))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
